version: '3.8'

services:
  # ==========================================
  # LOAD BALANCER LAYER (GERBANG DEPAN)
  # ==========================================
  nginx:
    image: nginx:alpine
    container_name: elasticsix_nginx
    restart: always     # 👈 [TRICK SRE] Babysitter aktif! NGINX akan otomatis bangkit kalau mati.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # Membuka Port 80 di laptopmu (Default HTTP)
    depends_on:
      - api
    networks:
      - elasticsix_net

  # ==========================================
  # API LAYER
  # ==========================================
  # 1. API Service (Golang)
  api:
    container_name: elasticsix_api
    build: .
    restart: always     # 👈 [TRICK SRE] Babysitter aktif! API Golang akan otomatis bangkit kalau kalah balapan waktu (Race Condition).
    # FIX BENTROK 1: Port luar diubah ke 8000 agar kamu tetap bisa menjalankan 'go run main.go' di port 8080 laptopmu
    ports:
      - "8000:8080"
    environment:
      - DB_MASTER_URL=postgres://root:password@postgres:5432/bank_a_db?sslmode=disable
      - DB_REPLICA_URL=postgres://root:password@postgres_replica:5432/bank_a_db?sslmode=disable
    depends_on:
      - postgres
      - postgres_replica
      - redis
      - rabbitmq
    networks:
      - elasticsix_net

  # ==========================================
  # DATABASE & CACHE / QUEUE LAYER
  # ==========================================
  # 2. Database MASTER (PostgreSQL) - Khusus untuk Worker / Insert
  postgres:
    image: postgres:15-alpine
    container_name: elasticsix_postgres_master
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_a_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_master:/var/lib/postgresql/data
    networks:
      - elasticsix_net

  # 3. Database REPLICA (PostgreSQL) - Khusus untuk Read API & Circuit Breaker
  postgres_replica:
    image: postgres:15-alpine
    container_name: elasticsix_postgres_replica
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_a_db
    # FIX BENTROK 2: Port luar diset ke 5433 agar tidak berebut dengan port 5432 milik Master
    ports:
      - "5433:5432"
    networks:
      - elasticsix_net

  # 4. Caching (Redis)
  redis:
    image: redis:7-alpine
    container_name: elasticsix_redis
    ports:
      - "6379:6379"
    networks:
      - elasticsix_net

  # 5. Message Queue (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: elasticsix_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elasticsix_net

  # ==========================================
  # OBSERVABILITY & MONITORING LAYER
  # ==========================================

  # 6. Prometheus (Pengepul Metrik)
  prometheus:
    image: prom/prometheus:latest
    container_name: elasticsix_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - elasticsix_net

  # 7. Grafana (Dashboard Visualisasi)
  grafana:
    image: grafana/grafana:latest
    container_name: elasticsix_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - prometheus
    networks:
      - elasticsix_net
  
  # 8. Redis Exporter (Pengepul Metrik Cache)
  redis-exporter:
    image: oliver006/redis_exporter:alpine
    container_name: elasticsix_redis_exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - elasticsix_net

networks:
  elasticsix_net:
    driver: bridge

volumes:
  pgdata_master: