FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download || true
RUN CGO_ENABLED=0 GOOS=linux go build -o baseline-server ./cmd/baseline/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/baseline-server .
EXPOSE 8080
CMD ["./baseline-server"]
