global:
  scrape_interval: 5s # Prometheus akan menyedot data setiap 5 detik (cocok untuk Load Test biar real-time!)
  evaluation_interval: 5s

scrape_configs:
  # 1. Memantau kesehatan Prometheus itu sendiri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2. Memantau API Golang buatan Fathur/Sakha
  - job_name: "golang_api"
    static_configs:
      - targets: ["api:8080"] # Mengarah ke nama service 'api' di docker-compose
  
  # 3. Memantau Message Queue RabbitMQ
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"] # 15692 adalah port default metrik RabbitMQ


  # (Nanti kita bisa tambah target untuk RabbitMQ dan PostgreSQL di sini)
