global:
  scrape_interval: 5s # Prometheus akan menyedot data setiap 5 detik (cocok untuk Load Test biar real-time!)
  evaluation_interval: 5s

scrape_configs:
  # 1. Memantau kesehatan Prometheus itu sendiri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2. Memantau 3 Instance API Golang (Load Balanced)
  - job_name: "golang_api"
    static_configs:
      - targets: ["api1:8080", "api2:8080", "api3:8080"]
  
  # 3. Memantau Message Queue RabbitMQ
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"] # 15692 adalah port default metrik RabbitMQ

  # 4. Memantau Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
